### ISSUE TITLE
Error al asignar jugadores 

### ISSUE THREAD

**Issue by casti-lob** [casti-lob/ProyectoEntorno#2]
Inma a la hora de introducir el tipo de jugador numero 3 se introduce en (JuegoGUI juego = new JuegoGUI(ordenJugadores);) y de ahí va hacia el metodo 
public Element obtenerElementoTablero(Coordenada coord) {
		return tablero.get(coord);
	}
y provoca un NullPointerException. He estado mirando pero no se que es lo que tengo mal.

**Comment by ioliasa** [comment]
Buenos días, vamos a ver, dónde has creado el tablero????? Yo no lo veo en ningún sitio. El constructor del juego qué tiene que hacer?. Tiene que dejar todos los atributos preparados, tu lo dejas? Y cuando llamas a crear los elementos y los jugadores?
